### ISSUE TITLE
Problema 

### ISSUE THREAD

**Issue by cristiancolombo87** [EtheaDev/StyledComponents#1]
Compilando con Delphi 10.2 mi da errore sulla IDETheme.Utils. Da dove la aggiungo?

**Comment by carloBarazzetta** [comment]
faccio una prova e ti dico...

**Comment by cristiancolombo87** [comment]
Se provo a installare o compilare il progetto dclStyledComponents.dproj da errore nella Vcl.StyledButtonEditorUnit.pas alla riga 129 "Unit 'IDETheme.Utils' not found"

**Comment by carloBarazzetta** [comment]
Hai installato l'ultima patch di Delphi 10.2 (Update 3)?
![image](https://user-images.githubusercontent.com/7803548/202294388-0190cb85-0646-4b74-bd95-e91069f44d68.png)

**Comment by cristiancolombo87** [comment]
No..sono fermo all'Update 1

**Comment by carloBarazzetta** [comment]
Dipende da quello: comunque se togli quella uses compila ugualmente, solo che il component editor si vede meno bene, credo che non si adatta allo stile scelto nell'IDE. In ogni caso ti consiglio vivamente di aggiornare le patch...
