### ISSUE TITLE
index

### ISSUE THREAD

**Issue by limelect** [EtheaDev/StyledComponents#10]
1.how do i change the index to imagelist? i cannot
2.glyph sould recieve what format? as i have my own expert and
it does not see my choice

**Comment by carloBarazzetta** [comment]
Delphi version?
1.I've notice a problem with the "property editor" but that non link correctly the property editor (in Delphi 11 and 12 works fine).  At the moment you can set imagelist manually, using a number...
2.Same similar problem: In D11 and D12 gliph accept all graphics format available in Delphi and works fine, in previous versions Accept only bmp...

**Comment by carloBarazzetta** [comment]
1.will be fixed soon.
2.I've notice that Glyph property of "native" TBitBtn from Delphi 10.4 can load only .bmp files... same as my TStyledButton, so I don't know why "your expert" don't show other format. For example, I'm using DevExpress and the property editor for Glyphs works file also to my StyledButtons...

**Comment by limelect** [comment]
D10.2.3
