### ISSUE TITLE
Delpgi 11.3 Compile But Not Install

### ISSUE THREAD

**Issue by celibol** [EtheaDev/StyledComponents#14]
For Delphi 11.3 give an error

![image](https://github.com/EtheaDev/StyledComponents/assets/202543/2444a430-788f-4ab9-a19a-391ebd293af8)

**Comment by carloBarazzetta** [comment]
No problems for me (Delphi 11.3).
Please try to exit and re-enter into IDE:
![image](https://github.com/EtheaDev/StyledComponents/assets/7803548/92817300-ae87-456b-8620-c9b3c67e608d)

**Comment by carloBarazzetta** [comment]
Check in your disk if you have another version of StyledComponents280.bpl and dclStyledComponents280.bpl: they should be located into C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\StyledComponents280.bpl folder.

**Comment by carloBarazzetta** [comment]
Resolved? Please give me a feedback to close the issue...

**Comment by carloBarazzetta** [comment]
No feedback... bye
