### ISSUE TITLE
TStyledButton issue

### ISSUE THREAD

**Issue by ASOFTSRL** [EtheaDev/StyledComponents#15]
Good morning Carlo,
I was trying your components before replacing some of the ones I currently use under certain circumstances.

TStyledButton:
Would it not be possible to introduce the TRANSPARENT property as for TStyledSpeedButton or TStyledGraphicButton ?

For all the button types mentioned in the line above:
- At Design Time I associate an Action ( with an image and a caption defined ) which are reported correctly in the property of TStyledButton.
- I remove the Caption manually from the object inspector ( In that button I only want the image and not the caption )
- At runtime it puts back the caption ( it takes from the action associated with the button ).

I solved it by forcing the caption:='' in create event of the form but couldn't you register the change in the .dfm so that even at runtime it reads that information directly ?

Thanks

Alberto

**Comment by carloBarazzetta** [comment]
Hello Alberto, the Transparent property is already present in TStyledGraphicButton (default false) and TStyledSpeedButton (default True).
For the Problem with Caption and the Action I'll investigate: I'm sure in past works, it's probably an error introduced in the last version...

**Comment by ASOFTSRL** [comment]
Hi Carlo,
I misunderstood ...I would like the Transparent property to also be introduced in TStyledButton ...is it possible ?

**Comment by carloBarazzetta** [comment]
I've made some tests with Caption, but it seems that also standard TButton, TBitBtn and TSpeedButtons restore the Caption... The only way is to store a "blank" caption using a single space, so in the dfm the Capion = ' ' is stored and at runtime is used instead of Action Caption...

**Comment by ASOFTSRL** [comment]
...and you can't extend the Transparent property to TStyledButton as well like TStyledGraphicButton and TStyledSpeedButton

**Comment by carloBarazzetta** [comment]
No because in Delphi a transparent component can be only a "graphic" component: StyledButton inherits from a TCustomControl, that cannot be transparent, having a Windows Handle... This is the main difference from TStyledButton and TStyledGraphicButton. You can use TStyledGraphicButton but you loose TabStop capability...

**Comment by ASOFTSRL** [comment]
Good morning Carlo,
I would like to ask, if it is possible for you, add a futures in a next release a property ShowCaption (true/false) in TStyledSpeedButton and in the other StyledButton ( TStyledToolbar has ShowCaption property ) that disables the caption display without put '' in the caption at runtime.

**Comment by carloBarazzetta** [comment]
Added to actual 3.4.5 version, give me a feedback if it works fine...

**Comment by ASOFTSRL** [comment]
Good morning Carlo,
yes ! ...it work fine.

I appreciate your work and support.

Thanks
Alberto
