### ISSUE TITLE
A suggestion for TStyledCategoryButtons

### ISSUE THREAD

**Issue by duancy** [EtheaDev/StyledComponents#16]
TStyledCategoryButtons It is recommended to add an icon position property, which can be customized to the left or right of the Categorys, similar to the NavMenu on the web 
![web_nav](https://github.com/EtheaDev/StyledComponents/assets/7732067/da2919ba-ea6b-4f43-92ad-bfc57bb54048)

**Comment by carloBarazzetta** [comment]
You can already do it: look at the StyledCategorybuttonsDemo.
You can change position for every buttons using ImageAlignment, and control the spacing using ImageMargins.
![image](https://github.com/EtheaDev/StyledComponents/assets/7803548/6a945ad9-d4cc-45af-8c8f-97375e99a847)

**Comment by duancy** [comment]
I want the icon in this position
![7041a43ec1621f9f82dbbeaee06b5700](https://github.com/EtheaDev/StyledComponents/assets/7732067/e392aa28-56c4-4501-ae2a-e4531637a107)

**Comment by carloBarazzetta** [comment]
Sorry but the title of the Categories are controlled by the VCL component: My version inherites from that and redraw only the button items, not the title.
