### ISSUE TITLE
Windows 10 - Caption of Toolbar Buttons on Delphi 10 Seattle  

### ISSUE THREAD

**Issue by hadi-pirhadi-at-limex-de** [EtheaDev/StyledComponents#18]
Hello Carlo,
I am very interested to meet your unique components on GitHub. 
When I tried to use the StyledToolbar in the form, unfortunately, the captions of the buttons cannot be displayed in Windows 10 at Design Time and also Run Time. But the caption of buttons when you try to change the style of them are available in dialog window. I tried to find and fix it but unfortunately I couldn't. 
Do you have any ideas ?

Thank you in advanced.
Hadi

**Comment by carloBarazzetta** [comment]
Are you using the latest version?
Probably was fixed here:
12 May 2024: version 3.5.2
Fixed Storing Caption of StyledToolButton

**Comment by hadi-pirhadi-at-limex-de** [comment]
Yes I used the latest version.
![StyledComponent](https://github.com/EtheaDev/StyledComponents/assets/88423354/783490cc-fff8-40fc-b95e-eb8c82961562)

**Comment by hadi-pirhadi-at-limex-de** [comment]
https://stackoverflow.com/questions/44632834/ttoolbar-stops-displaying-button-captions-after-a-while

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.0 version
