### ISSUE TITLE
Wrap the Button Text

### ISSUE THREAD

**Issue by hraztan** [EtheaDev/StyledComponents#2]
Hi. I just started fiddling with StyledComponents. Great work!!
Is there any way to wrap the button text?

**Comment by carloBarazzetta** [comment]
Currently, button text is rendered into:
procedure TStyledGraphicButton.DrawText(
I'm using Winapi.Windows.DrawText(

**Comment by hraztan** [comment]
I achieved the desired result by adding DT_WORDBREAK and DT_CENTER to the "Flag" parameter when calling the "CanvasDrawText" procedure in the "TStyledGraphicButton.DrawText" procedure.

`CanvasDrawText(Canvas, AText, R, AFlags or DT_CALCRECT or DT_WORDBREAK or DT_CENTER);`

`CanvasDrawText(Canvas, AText, R, AFlags or DT_WORDBREAK or DT_CENTER);`
