### ISSUE TITLE
Errore in order of the TStyledToolButton in TStyledToolbar 

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#23]
When i add a TStyledToolButton on a TStyledToolbar and change the order of the button, at design time the order is ok, bun at run time the the order of the TStyledToolButton is not correct.
3.60 installed on Delphi 11.2

**Comment by carloBarazzetta** [comment]
I know this bug, at the moment you can fix it editing the dfm file and change the order of the TStyledToolButton according to the creation order. I'll fix it as soon as possible.

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.1
