### ISSUE TITLE
Separator Width and problem when copy a button aon tpanel

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#24]
Very Well and congratulation.
First problem.
There is a mode to change the witdth of a separator present in a TStyledToolButton or in a TPanel. At design thime the witdth is correct (is the width i impost manually) but a run time the width is too small. I TRIED the same thing on a normal Tpanel but the width of a separator dont change. It remain small.
Second problem:
When i copy a TStyledToolButton from a TStyledToolbar on a Tpanel does not copy the Stylefamily, style class, etc. I have to set them manually after copy.
third problem:
I create a Tpanel with a TStyledToolButton without image and only a caption, with height=60. At Design time ok, but a run time the hieght of TStyledToolButton i resized at 10. Is correct ? There is a modo to force the Height as at design time ?
What is the differete between tbsseparator and tbsdivider ?
fourth problem:
When insert a TStyledToolbar on a Tpanel with an image then imagealignment don't function. The image remain at left, and the caption remain at right.

**Comment by carloBarazzetta** [comment]
Hy Mauro, please add those problems as separated issues, so I can resolve them one by one.
Thanks.

**Comment by carloBarazzetta** [comment]
Answered to other single issue
