### ISSUE TITLE
copy a TStyledToolButton from a TStyledToolbar on a Tpanel

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#26]
When i copy a TStyledToolButton from a TStyledToolbar on a Tpanel does not copy the Stylefamily, style class, etc. I have to set them manually after copy.

**Comment by carloBarazzetta** [comment]
You can copy and place a StyledToolButton directly on a Form or Panel, but it's a bug... It's a miracle that a StyledToolButton works outside a StyledToolbar. Use a StyledButton instead if you need a button outside a Toolbar.
