### ISSUE TITLE
Problem to paint TStyledToolbar on a tpanel. The image remain at left, and the caption remain at right.

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#28]
When insert a TStyledToolbar on a Tpanel with an image then imagealignment don't function. The image remain at left, and the caption remain at right.

**Comment by carloBarazzetta** [comment]
Please specify or report here your component difinitions (dfm) or an Image that explain the problem...
Are you using "ShowCaptions" or "List"? List force always icons to the left. Using ShowCaptions you can set alignment as you want.
![image](https://github.com/user-attachments/assets/4bfb8595-4423-4e84-9a39-9562ad8a165a)
