### ISSUE TITLE
width of a separator present in a TStyledToolButton

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#29]
There is a mode to change the width of a separator present in a TStyledToolButton. At design thime the witdth is correct (is the width i impost manually) but a run time the width is too small.

**Comment by carloBarazzetta** [comment]
You can fix it removing line 990 from Vcl.StyledToolbar.pas and add this line (at position 397) in Vcl.StyledComponentsRegister.pas
LNewButton.Width := DEFAULT_TOOLBUTTON_SEP_WIDTH;
the rebuild packages...

**Comment by MAUROFAILO** [comment]
Perfect.

**Comment by carloBarazzetta** [comment]
Please give me a feed-back if the problem is resolved for you!
