### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JFSF** [EtheaDev/StyledComponents#3]
You should mention in your documentation that the units: Vcl.AngularButtons, Vcl.BootstrapButtons and Vcl.StandardButtons should also be included in the application uses declaration, since without these units in runtime there's no change in appearence.

**Comment by carloBarazzetta** [comment]
In future version the uses needed are automatically added to the units.

**Comment by carloBarazzetta** [comment]
Fixed in 2.0.0 version
