### ISSUE TITLE
about TStyledToolbar.SetButtonWidth

### ISSUE THREAD

**Issue by marcuscde** [EtheaDev/StyledComponents#37]
Hi, i'm wondering if the "ResizeButtons" can be put into a conditional, and it can check a property of the toolbar, so it can be disabled if not wanted? This will make it so the buttons can have different widths if needed.

Thanks

**Comment by carloBarazzetta** [comment]
StyledToolbar works as a standard Toolbar (without ShowCaption enabled): when you resize a toolbutton all buttons of the toolbar resize at the same value, forcing the toolbar ButtonWidth property. The standard toolbar have different button size when ShowCaption is True, based on Caption size of every button, but I hate this...
Notice that StyledToolbar inherits from FlowPanel, so you can implement a Toolbar using a FlowPanel, adding TSyledButtons and define size of every single button as you want...

**Comment by carloBarazzetta** [comment]
Resolved?
