### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SergioIsBack** [EtheaDev/StyledComponents#4]
Hi, I need to write applications for french people, so a minor change would be appreciated :

Move the ButtonName from implementation section to interface section inside Vcl.StyledTaskDialog.pas
With this little adjustment it could be possible to use differents languages in user interface 👍 

Example:

// French
ButtonNames[mbYes]:='Oui';
ButtonNames[mbNo]:='Non';

//German
ButtonNames[mbYes]:='Ja' ;
ButtonNames[mbNo]:='Nein';

 // with resourcestrings
resourcestring
   MB_YESSTR_SPANISH = 'Si';
   MB_NOSTR_SPANISH = 'No';

....
ButtonNames[mbYes]:=MB_YESSTR_SPANISH ;
ButtonNames[mbNo]:=MB_NOSTR_SPANISH ;

**Comment by SergioIsBack** [comment]
For TaskMessage it is also possible to add this translated messages for french support :

{$ELSE IFDEF FraMessages}
    STR_YES = 'Oui';
    STR_NO = 'Non';
    STR_OK = 'Ok';
    STR_CANCEL = 'Annuler';
    STR_ABORT = 'Abandonner';
    STR_RETRY = 'Réessayer';
    STR_IGNORE = 'Ignorer';
    STR_UNDO = 'Défaire';
    STR_ALL = 'Tous';
    STR_NOTOALL = 'Non à tout';
    STR_YESTOALL = 'Oui à tout';
    STR_HELP = 'Help';
    STR_ABOUT = 'A propos';
    STR_WARNING = 'Attention';
    STR_ERROR = 'Erreur';
    STR_INFORMATION = 'Information';
    STR_CONFIRM = 'Confirmer';
    STR_CLOSE = 'Fermer';
    EINSTANTERRORDESC = 'Erreur de données';
    EDATABASEERRORDESC = 'Erreur de données';
    EGENERICERROR = 'Erreur';
    EACCESSVIOLDESC = 'Violation d''accès';
    ERR_ACCES_VIOL_DESC = 'Une erreur non gérée a été detectée.'+sLineBreak+sLineBreak+'%s'+sLineBreak+sLineBreak+
                          'Il est recommandé de fermer et de relancer l''application.'+sLineBreak+
                          'Si le programme persiste, contactez le support technique.';

**Comment by carloBarazzetta** [comment]
I'm working on a new version, adding full support of any VCL style applied to "Classic" styled button, so I'll add your suggestions as well. Stay tuned!

**Comment by carloBarazzetta** [comment]
Fixed in 2.0.0 version

**Comment by carloBarazzetta** [comment]
@SergioIsBack, can you help me for the correct translation of French DbNavigator? I'm developing a StyledDbNavigator...

**Comment by SergioIsBack** [comment]
@carloBarazzetta : Hello, if you send me the source (or the strings), yes I can help you translate strings in French

**Comment by carloBarazzetta** [comment]
//Navigator buttons Captions
    CaptionFirstRecord = 'First';
    CaptionPriorRecord = 'Prior';
    CaptionNextRecord = 'Next';
    CaptionLastRecord = 'Last';
    CaptionInsertRecord = 'Insert';
    CaptionDeleteRecord = 'Delete';
    CaptionEditRecord = 'Edit';
    CaptionPostEdit = 'Post';
    CaptionCancelEdit = 'Cancel';
    CaptionConfirmCaption = 'Confirm';
    CaptionRefreshRecord = 'Refresh';
    CaptionApplyUpdates = 'Apply';
    CaptionCancelUpdates = 'Revert';
    //Navigator buttons Hints
    SFirstRecord = 'First record';
    SPriorRecord = 'Prior record';
    SNextRecord = 'Next record';
    SLastRecord = 'Last record';
    SInsertRecord = 'Insert record';
    SDeleteRecord = 'Delete record';
    SEditRecord = 'Edit record';
    SPostEdit = 'Post edit';
    SCancelEdit = 'Cancel edit';
    SConfirmCaption = 'Confirm';
    SRefreshRecord = 'Refresh data';
    SApplyUpdates = 'Apply updates';
    SCancelUpdates = 'Revert updates';
    SDeleteRecordQuestion = 'Delete record?';

**Comment by SergioIsBack** [comment]
Hi @carloBarazzetta, French translations bellow :

//Navigator buttons Captions
CaptionFirstRecord = 'Premier';
CaptionPriorRecord = 'Précédent';
CaptionNextRecord = 'Suivant';
CaptionLastRecord = 'Dernier';
CaptionInsertRecord = 'Insérer';
CaptionDeleteRecord = 'Supprimer';
CaptionEditRecord = 'Editer';
CaptionPostEdit = 'Valider';
CaptionCancelEdit = 'Abandonner';
CaptionConfirmCaption = 'Confirmer';
CaptionRefreshRecord = 'Rafraichir';
CaptionApplyUpdates = 'Appliquer';
CaptionCancelUpdates = 'Annuler';
//Navigator buttons Hints
SFirstRecord = 'Premier enregistrement';
SPriorRecord = 'Enregistrement précédent';
SNextRecord = 'Enregistrement suivant';
SLastRecord = 'Dernier enregistrement';
SInsertRecord = 'Insérer un enregistrement';
SDeleteRecord = 'Supprimer l''enregistrement';
SEditRecord = 'Editer l''enregistrement ';
SPostEdit = 'Valider les modifications';
SCancelEdit = 'Abandonner les modifications';
SConfirmCaption = 'Confirmer';
SRefreshRecord = 'Rafraichir les données';
SApplyUpdates = 'Appliquer les modifications';
SCancelUpdates = 'Annuler les modifications';
SDeleteRecordQuestion = 'Supprimer l''enregistrement?';

**Comment by carloBarazzetta** [comment]
Included in version 3.0.
Thanks.
