### ISSUE TITLE
Infomation how create a StyledTaskDialog at runtime with verification procedure.

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#40]
Buon giorno Carlo. 
Scusami per il disturbo e se scrivo in italiano.
Per personalizzare e velocizzare la visualizzazione di un messaggio ho creato una apposita semplice procedura, che crea a runtime una StyledTaskDialog e dovrebbe abilitare il tasto "OK" al momento del click sulla Chechbox relativa alla "Verifica di conferma".
Dovrei quindi  penso collegare all'evento OnVerificationClicked dell'oggetto StyledTaskDialog creato una procedura che abilita il tasto "OK".
Ho provato in tutti i modi. Il codice sotto riportato è compilabile, ma il valore "Sender" inviato alla procedura è sempre NIL e quindi non riesco ad abilitare il tasto "OK".
Hai qualche soluzione ? Sbaglio qualcosa ? Il collegamento all'evento OnVerificationClicked è corretto ?
Il codice proposto è il seguente.
Grazie e scusami per il disturbo.

PS. Sarebbe bello, se ci fosse la possibilità nella demo StyledTaskDialogDemo di inserire un memo in cui visualizzare il codice delphi da "Incollare" nei propri software.

Procedure StyledTaskDialogVerificationClicked(Sender: TObject);
begin
  if (tfVerificationFlagChecked in (Sender as TStyledTaskDialog).Flags) then
    (Sender as TStyledTaskDialog).CommonButtons:=(Sender as TStyledTaskDialog).CommonButtons + [tcbOK]
  else
    (Sender as TStyledTaskDialog).CommonButtons:=(Sender as TStyledTaskDialog).CommonButtons - [tcbOK];
end;

Function CreateConfirmDialogOKNOWithVerificationTest(Messaggio:String):TStyledTaskDialog;
Var StyledTaskDialog1:TStyledTaskDialog;
      M: TMethod;
Begin
  StyledTaskDialog1:=TStyledTaskDialog.create(Nil);
  try
    With StyledTaskDialog1 do
    Begin
      mainIcon:=tdiWarning;
      Caption:='Richiesta di conferma';
      Title:='Attenzione:';
      Text:= Messaggio;
      VerificationText:='Verifica di conferma';
      CommonButtons:=[tcbNO];
      DefaultButton:=tcbNO;
      m.Data := StyledTaskDialog1;
      m.Code := @StyledTaskDialogVerificationClicked;
      OnVerificationClicked := TNotifyEvent(M);
      Execute;
      If (Modalresult=MrOk) then ShowMessage('Hai selezionato ok. Bravo!!!!');
    End;
  finally
    StyledTaskDialog1.free;
  end;

**Comment by carloBarazzetta** [comment]
Zippami un progetto completo di demo così lo posso compilare e verificare cosa non funziona...

**Comment by MAUROFAILO** [comment]
[TestDialog.zip](https://github.com/user-attachments/files/16982858/TestDialog.zip)
Grazie per la disponibilità.

**Comment by MAUROFAILO** [comment]
Ho verifiato. TTaskDialog non permette di abilitare (attraverso l'esecuzuione dell'evento Validation) i necessari Button presenti sul Dialog. Peccato.
La mia esigenza era quella di utilizzare il "Check di valitazione" per attivare il tasto OK. (doppia conferma necessaria ad esempio per l'esecuzione di qualcosa di importante).

**Comment by carloBarazzetta** [comment]
Te lo sto implementando...

**Comment by MAUROFAILO** [comment]
Grazie carlo per la disponibilità ... ma non volevo farti perdere tempo ... ma mi sembrava una cosa utile.
