### ISSUE TITLE
Change the laguage of the button caption in TStyledTaskDialog.

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#41]
Can i modify the caption of the button in TStyledTaskDialog with the System language. 
In the demo, if i use TStyledTaskDialog then button caption is only in english language.
If i use TaskDialog the language is corrent and rispects the system language.

**Comment by carloBarazzetta** [comment]
At the moment, you can activate the {$Define ItaMessages} into StyledComponents.inc file, but I'm working on use of system language...

**Comment by MAUROFAILO** [comment]
Perfect
