### ISSUE TITLE
Boarder Background does not match parent background

### ISSUE THREAD

**Issue by Larrydew** [EtheaDev/StyledComponents#43]
I am trying to use a TStyleBitBtn over a background. At design time everything looks correct, however at runtime the background boarder of the button is not correct.  See below.
Thanks

-- 
![StyleBitButton](https://github.com/user-attachments/assets/8fb9d52f-9843-4f83-bf36-2d73c04078f0)

**Comment by carloBarazzetta** [comment]
Please send me a zip with a test project.

**Comment by carloBarazzetta** [comment]
Please take a look at the new StyledComponents\Demos\Delphi??\StyledComponentsDemo.dproj and open the StyledTaskDialog Demo: you can use a more beautiful StyledDialog form also with "animations" (enabling SKIA to the project)...

**Comment by carloBarazzetta** [comment]
Any feedback?

**Comment by carloBarazzetta** [comment]
Fixed in 3.7.0 version
