### ISSUE TITLE
Suggest: StyledDBNavigator

### ISSUE THREAD

**Issue by vafadar1977** [EtheaDev/StyledComponents#45]
I need to add the custom button with actions (OnClick,...)  to styledDBNavigator. (similar to woll2woll dbnavigator)

**Comment by carloBarazzetta** [comment]
what kind of custom button? Please send me an example made with woll2woll dbnacvigator...

**Comment by carloBarazzetta** [comment]
Sorry but custom buttons requires a lot of code because my components are compatible with standard VCL components, so the only buttons available are the buttons defined by VisibleButtons property.
