### ISSUE TITLE
WordWrap property and Padding margin

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#47]
1) TStyledSpeedButton does not have WordWrap property. Is it possible to insert it? If the text is long, the characters are printed near the edge. IS possible have a Memo Caption With carrige return ?
1) Is possibile a padding margin internal of a StyledButton ?

**Comment by MAUROFAILO** [comment]
![image](https://github.com/user-attachments/assets/8192f5e0-b0e8-4024-8acf-e9407a2c587d)
Example of button with large caption.

**Comment by carloBarazzetta** [comment]
1. TStyledSpeedButton was created only for backward compatibility to TSpeedButton (that haven't WordWrap). You must use TStyledGraphicButton, that have WordWrap property.
2. It's a bug o StyledButton, because don't works as classic TButton... I'll fix it, as soon as possible

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.7
