### ISSUE TITLE
StyledTaskDialog icon is not trasparent

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#48]
![image](https://github.com/user-attachments/assets/44a9d070-21df-4bfc-89e3-40b78bb28e18)
In TStyledTaskDialog then Image is not Trasparent.
The code i this:

Function CreateInformationDialogOK(Messaggio:String):TStyledTaskDialog;
Var StyledTaskDialog1:TStyledTaskDialog;
Begin
  StyledTaskDialog1:=TStyledTaskDialog.create(Nil);
  With StyledTaskDialog1 do
  Begin
    mainIcon:=tdiInformation;
    Caption:='Informazione';
    Title:='Attenzione:';
    Text:= Messaggio;
    CommonButtons:=[tcbOk];
    DefaultButton:=tcbOk;
  End;
  Result:=StyledTaskDialog1;
End;

**Comment by carloBarazzetta** [comment]
It's not a problem of transparency of the image, but of the panel that contains the image.
Please try to change ParentColor to True of IconContainer Panel into unit Vcl.StyledTaskDialogFormUnit.pas and give me a feedbck.
Thanks.

**Comment by MAUROFAILO** [comment]
![image](https://github.com/user-attachments/assets/a08715b9-f015-418c-84fe-34c8215a1ab0)
![image](https://github.com/user-attachments/assets/742fd4dd-c7e8-4888-91d6-5d5bf8d62de8)
No. The problem remain.

**Comment by MAUROFAILO** [comment]
I change to True too, Parentcolor of CentralPanel end Imagepanel (The Owner of IconContainer), but the problem is not resolved.

**Comment by MAUROFAILO** [comment]
The problem is Parentbackground. It must be set to True in all the panel and owner panel. Verify. Give me a feedbck. Thanks.
![image](https://github.com/user-attachments/assets/74c0aee8-f286-4e0b-a4c2-fbb96a5be297)

**Comment by MAUROFAILO** [comment]
![image](https://github.com/user-attachments/assets/21a2959b-49bf-4aeb-b2bc-c5ff6d013ebe)
Buon giorno Carlo,
Quest'ultima versione non ha ancora risolto l'errore di visualizzazione dell'icona nelle StyledTaskDialog.
Il problema secondo me (così io ho risolto) è la proprietà Parentbackground. Deve essere impostata a True sia nel pannello che negli oggetti proprietari (OWNER). Verifica e fammi sapere.

**Comment by carloBarazzetta** [comment]
Bungiorno, a me non da questo problema: che stile VCL stai usando?
Riesci a dirmi che è impostata la tua app oppure mi crei un esempio minimale e me lo passi con uno zip?
![image](https://github.com/user-attachments/assets/0e2dfe51-b2ad-4a49-932a-dbc7829634aa)

**Comment by MAUROFAILO** [comment]
uso "Sapphire kamri". Nelle altre form uso anche le componeti DevExpress (se può essere utile).

**Comment by carloBarazzetta** [comment]
Edita a mano il file Vcl.StyledTaskDialogFormUnit.dfm togliendo le righe:
82: ParentBackground = False
246: ParentBackground = False
e poi dimmi se va a posto... non so come mai

**Comment by MAUROFAILO** [comment]
OK. funziona.
