### ISSUE TITLE
StyledTaskDialog Issue.

### ISSUE THREAD

**Issue by ijbranch** [EtheaDev/StyledComponents#49]
I just updated StyledComponents into my D12.2.  StyledComponents v 3.6.7.
The StyledTaskDialg component from the Styled Components palette acts as a StyledAnimatedTaskDialog. i.e. the MainIcon is animated. :-(
Ian

**Comment by carloBarazzetta** [comment]
Updated via Getit or Cloning GitHub?
At design time, if yuo have installed the StyledAnimatedComponents package it uses Skia4Delphi and register the AnimatedStyledDialog into IDE: if you don't want to see the animations at design time uninstall this package.
At run-time, if you don't include Skia.Vcl.StyledTaskDialogAnimatedUnit but use only Vcl.StyledTaskDialogStdUnit the animations you can use a normal StyledDialogs without animations.

**Comment by ijbranch** [comment]
Hi Carlo,
              Updated via GetIt.
              Comment/suggestions noted.  Thank you.

Regards,
Ian
The Programmer's Credo:  We do these things not because they are easy, but because we thought they were going to be easy... ***@***.*** - 05/08/2016)

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.9 version
