### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by PeterPanino** [EtheaDev/StyledComponents#5]
How do we avoid the terrible flickering on the styled toolbar buttons when resizing the form?

**Comment by carloBarazzetta** [comment]
Are you using VCLStyles or in "non-styled" Windows?

**Comment by PeterPanino** [comment]
I just compiled the toolbar demo program.

**Comment by carloBarazzetta** [comment]
On my PC, flicker is visible only using VCL styles. The Flickering issue is also present in the standard toolbar... Probably caused by a WM_ERASEBACKGROUND sent to components in Styled mode... I'll investigate.

**Comment by QuietMinder** [comment]
确实闪烁 闪的很厉害

**Comment by carloBarazzetta** [comment]
Please check if problem persist with latest 3.2.0 version
