### ISSUE TITLE
VCL.StyledTaskDialogForm Access Violation

### ISSUE THREAD

**Issue by lancerasmussen** [EtheaDev/StyledComponents#50]
Need to add a sanity check in 

TStyledTaskDialogForm

After finding the button  in LStyledButton := FindButton(LButtonItem.ModalResult);
you need to check if the button was assigned before accessing with
    if Assigned(LStyledButton) then begin

**Comment by carloBarazzetta** [comment]
I'm working to fix this...

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.9 version
