### ISSUE TITLE
StyledTaskDialog Component Issue

### ISSUE THREAD

**Issue by ijbranch** [EtheaDev/StyledComponents#51]
At design time using 'Test dialog', I can't get the ExpandButton to show, nor the Expanded Text if I set tfExpandedByDefault true.

Regards,
Ian

**Comment by carloBarazzetta** [comment]
Because the exapand button is not implemented, at the moment...

**Comment by ijbranch** [comment]
Hi Carlo,
              Ahhh.  That will do it every time.  😊
              I await with bated breath.

Regards,
Ian
The Programmer’s Credo:  We do these things not because they are easy, but because we thought they were going to be easy… ***@***.*** - 05/08/2016)

**Comment by carloBarazzetta** [comment]
Fixed in 3.6.9 version
