### ISSUE TITLE
Access violation during installation

### ISSUE THREAD

**Issue by eyal55462** [EtheaDev/StyledComponents#53]
When trying to install the components on Delphi 11 I get an access violation during registration on module RTL280
Any idea why?

**Comment by carloBarazzetta** [comment]
Are you using this version and build packages manually or GetIt version?
Are you installing Vcl.StyledComponents.Groupproj or Vcl.StyledAnimatedComponents.groupproj ?

**Comment by eyal55462** [comment]
I tried both Getit and manual installation.
I tried to install only the Vcl.StyledComponents.Groupproj.
Didn't try to install the animated styles.
Thanks

**Comment by carloBarazzetta** [comment]
Are you using latest 11.3 version? It's a Professional or Enterprise version?
Please check in all of your disk (using Ultrasearch for example) that you have only a single version of file StyledComponents280.bpl located in C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl and dclStyledComponents.dcp located in folder C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp

**Comment by eyal55462** [comment]
I'm using 11.3 Architect version.
Any way I delete every related files that I found, reinstall and it seems to be OK now.
Thanks a lot!
