### ISSUE TITLE
Ver. 3.6.9 - Errore in Compilazione durante l'installazione dei componenti

### ISSUE THREAD

**Issue by ASOFTSRL** [EtheaDev/StyledComponents#55]
Carlo Buongiorno,
nell'installazione della versione 3.6.9 riscontro un problema di compilazione alla linea 633 del modulo VCL.StyledTaskDialogFormUnit
Vedi immagine allegata.

Ho Delphi 11 + patch

Questo è il codice dove riscontro il problema:

    {$IFDEF D10_1+}
    MessageScrollBox.UseWheelForScrolling := True;
    {$ENDIF}

Per il momento l'ho commentato.
Grazie

![Clip913](https://github.com/user-attachments/assets/7dd9cd3f-2e09-44d0-9378-82cf4234e0d9)

**Comment by carloBarazzetta** [comment]
Si, me ne sono già accorto... grazie per la segnalazione

**Comment by ASOFTSRL** [comment]
Con D11+ mi segnala ancora errore ...devo mettere D12+ per escluderlo

VCL.forms c'è nella tua unit ma nel VCL.forms .pas non trovo TScrollBoxHelper ....non capisco 

![image](https://github.com/user-attachments/assets/aae055b6-7acc-49df-80bd-fc2302cf1223)

**Comment by carloBarazzetta** [comment]
Probabilmente ti serve Delphi 11 Update 3:
![image](https://github.com/user-attachments/assets/802d568b-d7a9-4227-be62-c6959561c9c4)

**Comment by carloBarazzetta** [comment]
Comunque serve solo se hai un messaggio lungo un kilometro e la dialog mostra una scollbar per permetterti di leggerlo... e poterlo scrollare col mouse è comodo, ma se non usi mai messaggi lunghi non ti servirà.
