### ISSUE TITLE
Error Due to Missing vsf File in Delphi Community Edition - Request for Basic Theme Code

### ISSUE THREAD

**Issue by lovehyunju** [EtheaDev/StyledComponents#57]
Hello,

I'm currently using the Delphi Community Edition, but I'm encountering an issue where I can't run the demo due to a missing vsf file, which leads to an error.
Could you provide a basic example code for applying a default theme?
Any guidance on resolving this would be greatly appreciated.

Thank you!

``
Checking project dependencies...
Building StyledComponentsDemo.dproj (Debug, Win32)
brcc32 command line for "StyledComponentsDemo.vrc"
  c:\program files (x86)\embarcadero\studio\23.0\bin\cgrc.exe -c65001 StyledComponentsDemo.vrc -foStyledComponentsDemo.res 
[BRCC32 Error] StyledComponentsDemo.vrc(80): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Impressive_Dark.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(81): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Impressive_Dark_SE.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(82): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Impressive_Light.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(83): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Impressive_Light_SE.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(84): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_MineShaft.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(85): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Modern_Dark.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(86): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Modern_Light.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(87): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Polar_Dark.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(88): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_Polar_Light.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(89): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Windows11_WhiteSmoke.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(97): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Copper.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(98): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\CopperDark.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(99): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Coral.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(102): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Diamond.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(103): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Emerald.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(106): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Jet.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(111): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Radiant.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(116): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Sterling.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(118): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Vapor.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(119): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\Calypso.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(120): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\CalypsoLE.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(121): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\CalypsoSE.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(122): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\CalypsoSLE.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(123): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\FlatUILight.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(125): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\LuckyPoint.vsf
[BRCC32 Error] StyledComponentsDemo.vrc(126): file not found: C:\Users\Public\Documents\Embarcadero\Studio\23.0\Styles\MaterialOxfordBlue.vsf
Failed
Elapsed time: 00:00:00.2
``

**Comment by carloBarazzetta** [comment]
You must simply open "Projects/Options/Appearance" and select you styles, then save the Project and Build.
Enjoy!
