### ISSUE TITLE
"Issue with OnClick Event Not Being Ignored When StyleButton Enabled Property is Set to False"

### ISSUE THREAD

**Issue by lovehyunju** [EtheaDev/StyledComponents#59]
I used the `StyleButton` component and set `Enabled` to `False`, but the `OnClick` event still triggers and behaves as if `Enabled` were `True`.
Shouldn't the `OnClick` event be ignored when `Enabled` is set to `False`?

**Comment by lovehyunju** [comment]
Hello, I'm using TStyledButton to create custom buttons with StyledComponents, but I've encountered some issues:

1. I have three buttons: StyledButton1, StyledButton2, and StyledButton3.
2. Both StyledButton1 and StyledButton3 have their `OnClick` event connected to `StyledButton3Click`.
3. StyledButton2 has its `OnClick` event connected to `StyledButton2Click`.
4. Everything works fine when `Enabled` is set to `True`.
5. However, when `Enabled` is set to `False`, I experience some problems:
   - In `StyledButton3Click`, calling `TStyledButton(Sender).Name` returns the form name (e.g., Form2).
   - Also, when `Enabled` is `False`, clicking StyledButton2 triggers `StyledButton3Click`.

This behavior causes critical issues when the buttons are disabled. 
Any advice on how to resolve this problem would be greatly appreciated. Thank you.

**Comment by carloBarazzetta** [comment]
I'll investigate immediatly for this bug!

**Comment by carloBarazzetta** [comment]
Please, submit a zip with your sample, because I cannot reproduce the same issue...

**Comment by lovehyunju** [comment]
[StyledTest.zip](https://github.com/user-attachments/files/17625130/StyledTest.zip)

There are 6 StyleButton1 buttons, and 3 of them have their `Enabled` property set to `False`, so they are disabled. When a user clicks on an enabled button, the button's name is added to `ListBox1`.

**Comment by carloBarazzetta** [comment]
There is an mistake in your demo: you have attached the StyledButton3Click event also to the OnClick event of the Form. 
When you click on a disabled button the OnClick event of the form is invoked, in fact the Sender at that moment is Form2.
Check with this code:
``` Delphi
  if Sender is TForm then
  begin
    ListBox1.Items.Add(TForm(Sender).Name + ' : ' + BoolToStr(TForm(Sender).Enabled));
    ListBox1.TopIndex := ListBox1.Items.Count - 1;
  end
  else if Sender is TStyledButton then
  begin
    ListBox1.Items.Add(TStyledButton(Sender).Name + ' : ' + BoolToStr(TStyledButton(Sender).Enabled));
    ListBox1.TopIndex := ListBox1.Items.Count - 1;
  end;
```
