### ISSUE TITLE
Button style properties are restored to default after opening the project

### ISSUE THREAD

**Issue by vectoris** [EtheaDev/StyledComponents#6]
ButtonStyleDisabled, ButtonStyleHot, ButtonStyleNormal, ButtonStylePressed, ButtonStyleSelected.
If you change these properties and then open the project, these properties will return to their default values.

**Comment by carloBarazzetta** [comment]
I'm working to resolve this problem...

**Comment by carloBarazzetta** [comment]
Fixed in 3.2.0 version
