### ISSUE TITLE
TCategoryButton margins or internal Padding

### ISSUE THREAD

**Issue by MAUROFAILO** [EtheaDev/StyledComponents#61]
TCategoryButton.
I want a margin in the left side of the button as in the image.
![image](https://github.com/user-attachments/assets/01cd425f-90e3-4cdb-9065-9b1e637908d8)

To do this, I had to set ImageAlignmet=iaLeft and ImageMargins.left=12 of TCategoryButton  and set imageindex of the button to -1.
It is possible to provide a left margin before the caption of the button ?

**Comment by MAUROFAILO** [comment]
or/and It is possible to provide a left margin before the left border of button ?

**Comment by carloBarazzetta** [comment]
Try with "Spacing" property

**Comment by carloBarazzetta** [comment]
Feedback?
