### ISSUE TITLE
StyledTaskDialog Issue:

### ISSUE THREAD

**Issue by ijbranch** [EtheaDev/StyledComponents#62]
Win 11, D12.2 p1, 4k monitor, 32bit App, DPI Unaware.
I have added vcl.StyledTaskDialogFormUnit to the Project .dpr, and am experimenting still with StyledTaskDialog component added to the project unit.
I have added 4 CommandLink buttons.
When I run the App and call the dialog, it puts it at the top left of the screen and there doesn't appear to be able to tell it I want it to appear at screen center.
![image](https://github.com/user-attachments/assets/25bf5417-f18e-4e1d-bb96-042107ae0a70)

Have I missed something??

**Comment by carloBarazzetta** [comment]
Probably is a bug: please give me a zip with your test project, so I can debug  and fix it.

**Comment by ijbranch** [comment]
Here you go.
[Project21.zip](https://github.com/user-attachments/files/17657576/Project21.zip)
I'm surprised you don't support .rar files...

**Comment by carloBarazzetta** [comment]
Try with version 3.7.2 and give me your feedback.

**Comment by ijbranch** [comment]
Ahhh.  That's better:
![image](https://github.com/user-attachments/assets/491ead5c-229d-43ae-9734-b022a65cf5af)

**Comment by ijbranch** [comment]
What parameter will change the CommandLink Buttons width?
I tried 'ButtonsWidth' but it didn't make any difference.  I'm guessing that is for the standard dialog buttons?
![image](https://github.com/user-attachments/assets/2c489041-23b3-45d4-80c1-90598b1188fc)
I'd like to reduce the dialog width to that of the 'Note:'

**Comment by carloBarazzetta** [comment]
I'm working to add a specific value tdiQuestion for MainIcon and FooterIcon properties of TStyledTaskDialog.
ButtonsWidths only affect the normal buttons at the bottom of the Dialog.
Actually the with of a Button using CommandLink is alway the width of the Dialog Form.
Maybe in future I can add a HideCloseButton property to my TStyledDialog... now works as standard TaskDialog.

**Comment by ijbranch** [comment]
Hi Carlo
	Tks.
	>>  Actually the width of a Button using CommandLink is always the width of the Dialog Form.
	But there is no property to adjust the width of the dialog.
Ian

**Comment by ijbranch** [comment]
The ButtonWidth property only affects the 'CommonButtons', not the 'Buttons'.
With ButtonWidth set to 120 I see this:
![image](https://github.com/user-attachments/assets/454fcff6-c1e8-4cce-81a9-d6ec144481f0)
Note, only the CommonButton 'Cancel' has the 120 width.

**Comment by carloBarazzetta** [comment]
This is a bug...
For other customizations of Styled dialog you can customize the "GUI" form by yourself: notice that there is a base form Vcl.StyledTaskDialogFormUnit.pas that contains the logic of building the form and two other forms that inherits from this:
- Vcl.StyledTaskDialogStdUnit (for non animated dialog) that contains only the logic for the icons, using an ImageList
- Skia.Vcl.StyledTaskDialogAnimatedUnit (for animated dialog using Skia4Delphi) that contains the logic for the animated icons using SkAnimatedImage.
You can inherits from TStyledTaskDialogStd form and customize your form as you want, adding icons to every buttons, : remember to register your form using:
RegisterTaskDialogFormClass(TMyStyledTaskDialogStd);
It is possible that in future I can add some other feature to the form controlled by the StyledTaslDialog component...

**Comment by ijbranch** [comment]
Cheers.

**Comment by carloBarazzetta** [comment]
In 3.7.4 version you can find:
- Added tdiQuestion value to show a Question mark in TaskDialog
- Use Question Mark (icon ora animation) for MessageDlg and TaskDialog of mtConfirmation type
- Fixed DefaultButton for StyledDialog using MessageDlg and TaskDialog

**Comment by ijbranch** [comment]
Hi Carlo,
Excellent!  Thank you.
The only thing I would wish for now is a Width property fo the dialog...  ;-)

Regards & Tks again.

**Comment by ijbranch** [comment]
Excellent!  Thank you.  Much appreciated.
