### ISSUE TITLE
Button caption font color can't change

### ISSUE THREAD

**Issue by edalab-xrg** [EtheaDev/StyledComponents#63]

**Comment by carloBarazzetta** [comment]
Please provide more info...

**Comment by edalab-xrg** [comment]
At present, the font and color of the caption attribute of button can only be modified by styled, which cannot well meet the needs of personalization. In addition I need the round panel more, thank you very much for your response, thank you

| |
siruidz
|
|
***@***.***
|
---- Replied Message ----
| From | Carlo ***@***.***> |
| Date | 11/09/2024 19:34 |
| To | EtheaDev/StyledComponents ***@***.***> |
| Cc | edalab-xrg ***@***.***>,
Author ***@***.***> |
| Subject | Re: [EtheaDev/StyledComponents] Button caption font color can't change (Issue #63) |

Please provide more info...

**Comment by edalab-xrg** [comment]
At present, the font and color of the caption attribute of button can only be modified by styled, which cannot well meet the needs of personalization. In addition I need the round panel more, thank you very much for your response。
The focus of many users is on round buttons, round panels, and the demand for styled is not very strong.


| |
siruidz
|
|
***@***.***
|
---- Replied Message ----
| From | Carlo ***@***.***> |
| Date | 11/09/2024 19:34 |
| To | EtheaDev/StyledComponents ***@***.***> |
| Cc | edalab-xrg ***@***.***>,
Author ***@***.***> |
| Subject | Re: [EtheaDev/StyledComponents] Button caption font color can't change (Issue #63) |

Please provide more info...

**Comment by carloBarazzetta** [comment]
You can personalize a different Font Color of any StyledButton using the five properties:
ButtonStyleNormal, ButtonStylePressed, ButtonStyleSelected, ButtonStyleHot, ButtonStyleDisabled
You can set a unique or different FontColor for any "state" of your Button!

**Comment by edalab-xrg** [comment]
I see，thanks.
