### ISSUE TITLE
Dialog Text Cutoff

### ISSUE THREAD

**Issue by lancerasmussen** [EtheaDev/StyledComponents#67]
Dialog text appears to be cutoff if a longer dialog.  One screenshot is in my dev VM and happens as well as happens with several users.  And the other is running the exe outside of the VM on host computer, which appears fine.  So something is not consistent. 
I've had to manually override the height in the component source to add 40 to the height as a workaround.

[TaaskDialogCutoff.zip](https://github.com/user-attachments/files/18013940/TaaskDialogCutoff.zip)
<img width="1280" alt="Cuttoff" src="https://github.com/user-attachments/assets/b778484f-62e9-47a6-b16a-94e5e52d4107">
<img width="448" alt="Screenshot 2024-12-04 124058" src="https://github.com/user-attachments/assets/8db09dcc-150c-4829-a84d-7d23f3444c25">

**Comment by carloBarazzetta** [comment]
Please give me some infos: your video resolution and DPI.

**Comment by carloBarazzetta** [comment]
The problem is the wrong CRLF sequence: using #10#13 cause the problem. Try with sLineBreak or #13#10

**Comment by lancerasmussen** [comment]
Wow.  Great catch.  Stared at that for a long time and just didn't catch the inverted CRLF.   Thank you.  That resolved the issue.

**Comment by carloBarazzetta** [comment]
I always recommend to use sLineBreak instead of CR+LF chars... ;-)
